# ***************************************** Make file code *********************
# Author: Sanket Agarwal & Dhiraj Kudva (agarwal.220196, dhirajkudva)@tamu.edu
#Organisation: Texas A&M University
#Description: Machine problem 3, Compiles server source code.



#for compiling server.c
sample : echos.o 


echos.o: server.c 
	gcc -I. server.c -o server
#clean to discard previous .o files
clean:
	rm -f sample *.o core



