# ***************************************** Make file code *********************
# Author:	Sanket Agarwal & Dhiraj Kudva (agarwal.220196, dhirajkudva)@tamu.edu
#Organisation:	Texas A&M University
#Description:	Machine problem 1, Compiles server and client source code.



#for compiling server.c

server: server.c
	gcc -I . server.c -o echos

#for compiling client.c 

client: client.c
	gcc -I . client.c -o echo

#clean to discard previous .o files 
clean:
	$(RM) *.o



